import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

// componentes
import Header from "../components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransiotion from './../components/StairTransiotion';

/* Idealizando a fonte "jetbrainMono" */

const jetbrainsMono = JetBrains_Mono({
   subsets: ["latin"],
  weight:["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Andrei MZ.",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<
  {children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        
        <Header />
        <Analytics />
        
        <StairTransiotion />
        
        <PageTransition>{ children }</PageTransition>
    
        </body>
    </html>
  );
}
